export const DANG_NHAP_ACION = 'DANG_NHAP_ACION';
export const SET_DANH_SACH_NGUOI_DUNG = 'SET_DANH_SACH_NGUOI_DUNG';
export const SET_LAY_THONG_TIN_NGUOI_DUNG = 'SET_LAY_THONG_TIN_NGUOI_DUNG';
export const SET_MA_LOAI_NGUOI_DUNG = 'SET_MA_LOAI_NGUOI_DUNG';
export const DANG_KY_ACTION = 'DANG_KY_ACTION';
export const SET_THONG_TIN_TAI_KHOAN_ND = 'SET_THONG_TIN_TAI_KHOAN_ND';
export const DOI_MAT_KHAU_ACTION = 'DOI_MAT_KHAU_ACTION';